name: Backup Logs from VPS

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  

jobs:
  backup_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Create logs_backup directory
        run: mkdir -p logs_backup

      - name: Backup logs from VPS using password authentication
        run: |
          sshpass -p "${{ secrets.VPS_SSH_KEY }}" scp -o StrictHostKeyChecking=no -r ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/var/log/* logs_backup/


      - name: Commit and push logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add logs_backup/ || echo "No hay cambios en logs_backup"
          git diff --cached --quiet || (git commit -m "Backup de logs del VPS" && git push origin main)